In [1]:
import numpy as np
import pandas as pd

In [5]:
import scipy.stats as stats
from scipy.stats import skew, kurtosis, mode, binom, poisson, norm, expon

# Descriptive Statistics: describe()

In [7]:
np.random.seed(42)
data = pd.DataFrame({
    'Var1': np.random.rand(10),
    'Var2': np.random.rand(10),
    'Var3': np.random.rand(10),
    'Var4': np.random.rand(10),
    'Var5': np.random.rand(10),
    'c': ['X', 'X', 'Y', 'Y', 'Y', 'X', 'X', 'Y', 'Y', 'Y']
})

In [8]:
data.describe(include='all')

             Var1       Var2       Var3       Var4       Var5    c
count   10.000000  10.000000  10.000000  10.000000  10.000000   10
unique        NaN        NaN        NaN        NaN        NaN    2
top           NaN        NaN        NaN        NaN        NaN    Y
freq          NaN        NaN        NaN        NaN        NaN    6
mean     0.520137   0.395268   0.400387   0.509271   0.404557  NaN
std      0.315866   0.302371   0.233860   0.343095   0.270406  NaN
min      0.058084   0.020584   0.046450   0.065052   0.034389  NaN
25%      0.210649   0.190638   0.222791   0.204047   0.203336  NaN
50%      0.599887   0.297736   0.411216   0.523849   0.403444  NaN
75%      0.726014   0.501554   0.572870   0.777356   0.540050  NaN
max      0.950714   0.969910   0.785176   0.965632   0.909320  NaN

In [9]:
data.groupby(by='c')

In [52]:
''' describe: Calculate descriptive statistics for each numerical column in the DataFrame.df: DataFrame
        cols: list of numerical columns to compute statistics (optional)
        id_vars: id column
    Dependencies: pandas, numpy
'''
def describe(df: pd.DataFrame, cols=[], group=''):

    if group!='': df = df.pivot(columns=group) # Splits tidy dataframe
    if len(cols)>0: df = df[cols] # Isolate specified columns

    descriptive = pd.DataFrame()    
    descriptive['mean'] = df.mean() # Mean
    descriptive['median'] = df.median() # Median
    descriptive['variance'] = df.var() # Variance
    descriptive['std_dev'] = df.std() # Standard Deviation
    descriptive['mad'] = df.apply(lambda x: np.median(np.abs(x - x.median()))) # Median Absolute Deviation
    descriptive['min'] = df.min() # Minimum
    descriptive['max'] = df.max() # Maximum
    descriptive['range'] = df.max() - df.min() # Range
    descriptive['skewness'] = df.apply(lambda x: skew(x, nan_policy='omit')) # Skewness
    descriptive['kurtosis'] = df.apply(lambda x: kurtosis(x, nan_policy='omit')) # Kurtosis
    descriptive['count'] = df.count() # Count (non-missing observations)
    descriptive['sum'] = df.sum() # Sum
    descriptive['25%'] = df.quantile(0.25)  # Quantiles (25%, 50%, 75%)
    descriptive['50%'] = df.quantile(0.50)
    descriptive['75%'] = df.quantile(0.75)

    return descriptive

In [40]:
import pyMUZ.gen.io as io

In [41]:
lc = io.get('/Users/marczepeda/Documents/Liau_Lab/Projects/2.ZF_degraders/1.Molecular_Biology/MUZ120/NGS/out/LC_outcomes.csv')
lc

                         sample          edit  count  fraction
0     MUZ120-38_S38_L001_R1_001            WT   2712  0.546995
1     MUZ120-38_S38_L001_R1_001         H167R   2145  0.432634
2     MUZ120-38_S38_L001_R1_001  H163P, H167R      4  0.000807
3     MUZ120-38_S38_L001_R1_001  H167R, G169R      4  0.000807
4     MUZ120-38_S38_L001_R1_001  R143Q, H167R      3  0.000605
...                         ...           ...    ...       ...
1563  MUZ120-34_S34_L001_R1_001         G169W      1  0.000232
1564  MUZ120-34_S34_L001_R1_001  N159T, H191Y      1  0.000232
1565  MUZ120-34_S34_L001_R1_001         N179I      1  0.000232
1566  MUZ120-34_S34_L001_R1_001  F145L, N159T      1  0.000232
1567  MUZ120-34_S34_L001_R1_001         H163R      1  0.000232

[1568 rows x 4 columns]

In [48]:
describe(lc,cols=['count','fraction'])

,mean,median,variance,std_dev,mad,min,max,range,skewness,kurtosis,count,sum,25%,50%,75%
count,59.283163,1.000000,173362.998261,416.368825,0.000000,1.000000,5590.000000,5589.000000,8.880312,88.816906,1568,92956.0,1.000000,1.000000,1.000000
fraction,0.017219,0.000247,0.012536,0.111963,0.000084,0.000163,0.982928,0.982764,7.215052,53.050610,1568,27.0,0.000193,0.000247,0.000463

In [49]:
desc = describe(lc,cols=['fraction'],group='sample')

In [51]:
desc.loc['fraction']['25%']

sample
MUZ120-31_S31_L001_R1_001    0.000237
MUZ120-32_S32_L001_R1_001    0.000456
MUZ120-33_S33_L001_R1_001    0.000461
MUZ120-34_S34_L001_R1_001    0.000232
MUZ120-35_S35_L001_R1_001    0.000209
MUZ120-36_S36_L001_R1_001    0.000427
MUZ120-37_S37_L001_R1_001    0.000198
MUZ120-38_S38_L001_R1_001    0.000202
MUZ120-39_S39_L001_R1_001    0.000219
MUZ120-40_S40_L001_R1_001    0.000163
MUZ120-41_S41_L001_R1_001    0.000175
MUZ120-42_S42_L001_R1_001    0.000193
MUZ120-43_S43_L001_R1_001    0.000456
MUZ120-44_S44_L001_R1_001    0.000523
MUZ120-45_S45_L001_R1_001    0.000759
MUZ120-46_S46_L001_R1_001    0.000571
MUZ120-47_S47_L001_R1_001    0.000646
MUZ120-48_S48_L001_R1_001    0.000883
MUZ120-49_S49_L001_R1_001    0.000247
MUZ120-50_S50_L001_R1_001    0.000513
MUZ120-51_S51_L001_R1_001    0.000414
MUZ120-52_S52_L001_R1_001    0.000452
MUZ120-53_S53_L001_R1_001    0.000492
MUZ120-54_S54_L001_R1_001    0.000463
MUZ120-55_S55_L001_R1_001    0.000169
MUZ120-56_S56_L001_R1_001    0.000183
MUZ120-57_S57_L001_R1_001    0.000188
Name: 25%, dtype: float64

In [45]:
describe(lc,cols=['fraction'],group='sample')

                                        mean    median  variance   std_dev  \
         sample
fraction MUZ120-31_S31_L001_R1_001  0.012987  0.000237  0.006201  0.078743
         MUZ120-32_S32_L001_R1_001  0.021739  0.000456  0.020638  0.143659
         MUZ120-33_S33_L001_R1_001  0.023256  0.000461  0.013526  0.116300
         MUZ120-34_S34_L001_R1_001  0.015385  0.000232  0.008714  0.093351
         MUZ120-35_S35_L001_R1_001  0.011628  0.000209  0.011003  0.104896
         MUZ120-36_S36_L001_R1_001  0.028571  0.000427  0.027576  0.166060
         MUZ120-37_S37_L001_R1_001  0.013333  0.000198  0.011722  0.108268
         MUZ120-38_S38_L001_R1_001  0.011765  0.000202  0.005650  0.075168
         MUZ120-39_S39_L001_R1_001  0.012346  0.000219  0.010271  0.101344
         MUZ120-40_S40_L001_R1_001  0.009901  0.000163  0.004572  0.067617
         MUZ120-41_S41_L001_R1_001  0.013889  0.000175  0.013341  0.115504
         MUZ120-42_S42_L001_R1_001  0.011628  0.000193  0.005631  0.075041
         MUZ120-43_S43_L001_R1_001  0.022222  0.000456  0.012720  0.112782
         MUZ120-44_S44_L001_R1_001  0.027778  0.000523  0.026217  0.161918
         MUZ120-45_S45_L001_R1_001  0.040000  0.000759  0.038435  0.196048
         MUZ120-46_S46_L001_R1_001  0.032258  0.000571  0.029189  0.170849
         MUZ120-47_S47_L001_R1_001  0.033333  0.000646  0.016857  0.129835
         MUZ120-48_S48_L001_R1_001  0.047619  0.000883  0.038830  0.197053
         MUZ120-49_S49_L001_R1_001  0.014925  0.000247  0.007830  0.088487
         MUZ120-50_S50_L001_R1_001  0.029412  0.000513  0.028182  0.167874
         MUZ120-51_S51_L001_R1_001  0.022222  0.000414  0.011856  0.108887
         MUZ120-52_S52_L001_R1_001  0.025000  0.000452  0.013380  0.115673
         MUZ120-53_S53_L001_R1_001  0.025000  0.000492  0.023632  0.153727
         MUZ120-54_S54_L001_R1_001  0.022222  0.000463  0.021120  0.145327
         MUZ120-55_S55_L001_R1_001  0.009615  0.000169  0.008274  0.090960
         MUZ120-56_S56_L001_R1_001  0.013699  0.000183  0.007151  0.084566
         MUZ120-57_S57_L001_R1_001  0.012500  0.000188  0.010754  0.103703

                                    mad       min       max     range  \
         sample
fraction MUZ120-31_S31_L001_R1_001  NaN  0.000237  0.581771  0.581533
         MUZ120-32_S32_L001_R1_001  NaN  0.000456  0.974897  0.974441
         MUZ120-33_S33_L001_R1_001  NaN  0.000461  0.726602  0.726141
         MUZ120-34_S34_L001_R1_001  NaN  0.000232  0.703223  0.702991
         MUZ120-35_S35_L001_R1_001  NaN  0.000209  0.973075  0.972866
         MUZ120-36_S36_L001_R1_001  NaN  0.000427  0.982928  0.982501
         MUZ120-37_S37_L001_R1_001  NaN  0.000198  0.937797  0.937599
         MUZ120-38_S38_L001_R1_001  NaN  0.000202  0.546995  0.546793
         MUZ120-39_S39_L001_R1_001  NaN  0.000219  0.910706  0.910487
         MUZ120-40_S40_L001_R1_001  NaN  0.000163  0.504248  0.504085
         MUZ120-41_S41_L001_R1_001  NaN  0.000175  0.980358  0.980182
         MUZ120-42_S42_L001_R1_001  NaN  0.000193  0.566994  0.566802
         MUZ120-43_S43_L001_R1_001  NaN  0.000456  0.717609  0.717153
         MUZ120-44_S44_L001_R1_001  NaN  0.000523  0.972280  0.971757
         MUZ120-45_S45_L001_R1_001  NaN  0.000759  0.981032  0.980273
         MUZ120-46_S46_L001_R1_001  NaN  0.000571  0.952571  0.952000
         MUZ120-47_S47_L001_R1_001  NaN  0.000646  0.635659  0.635013
         MUZ120-48_S48_L001_R1_001  NaN  0.000883  0.904594  0.903710
         MUZ120-49_S49_L001_R1_001  NaN  0.000247  0.661059  0.660811
         MUZ120-50_S50_L001_R1_001  NaN  0.000513  0.979487  0.978974
         MUZ120-51_S51_L001_R1_001  NaN  0.000414  0.668321  0.667907
         MUZ120-52_S52_L001_R1_001  NaN  0.000452  0.671635  0.671183
         MUZ120-53_S53_L001_R1_001  NaN  0.000492  0.972933  0.972441
         MUZ120-54_S54_L001_R1_001  NaN  0.000463  0.975440  0.974977
         MUZ120-55_S55_L001_R1_001  NaN  0.000169  0.927534  0.927365
         MUZ120-56_S56_L001_R1_001  NaN  0.000183  0.644701  0.644518
         MUZ120-57_S57_L001_R1_001  NaN  0.000188  0.926985  0.926797

                                     skewness   kurtosis  count  sum  \
         sample
fraction MUZ120-31_S31_L001_R1_001   6.344116  39.681758     77  1.0
         MUZ120-32_S32_L001_R1_001   6.559096  41.021911     46  1.0
         MUZ120-33_S33_L001_R1_001   5.504120  29.973192     43  1.0
         MUZ120-34_S34_L001_R1_001   6.655020  44.806615     65  1.0
         MUZ120-35_S35_L001_R1_001   9.110785  81.008219     86  1.0
         MUZ120-36_S36_L001_R1_001   5.659441  30.029323     35  1.0
         MUZ120-37_S37_L001_R1_001   8.467692  69.803572     75  1.0
         MUZ120-38_S38_L001_R1_001   6.421744  39.806366     85  1.0
         MUZ120-39_S39_L001_R1_001   8.761694  75.149848     81  1.0
         MUZ120-40_S40_L001_R1_001   6.910534  45.881758    101  1.0
         MUZ120-41_S41_L001_R1_001   8.307431  67.013642     72  1.0
         MUZ120-42_S42_L001_R1_001   6.575016  42.242834     86  1.0
         MUZ120-43_S43_L001_R1_001   5.592348  31.044384     45  1.0
         MUZ120-44_S44_L001_R1_001   5.746662  31.025682     36  1.0
         MUZ120-45_S45_L001_R1_001   4.694851  20.041639     25  1.0
         MUZ120-46_S46_L001_R1_001   5.290121  26.002033     31  1.0
         MUZ120-47_S47_L001_R1_001   3.965126  14.691118     30  1.0
         MUZ120-48_S48_L001_R1_001   4.201504  15.783342     21  1.0
         MUZ120-49_S49_L001_R1_001   6.491168  42.567687     67  1.0
         MUZ120-50_S50_L001_R1_001   5.570466  29.030167     34  1.0
         MUZ120-51_S51_L001_R1_001   5.226300  26.978755     45  1.0
         MUZ120-52_S52_L001_R1_001   4.912984  23.645592     40  1.0
         MUZ120-53_S53_L001_R1_001   6.084615  35.023618     40  1.0
         MUZ120-54_S54_L001_R1_001   6.482458  40.022426     45  1.0
         MUZ120-55_S55_L001_R1_001  10.024901  98.664031    104  1.0
         MUZ120-56_S56_L001_R1_001   6.580739  43.626499     73  1.0
         MUZ120-57_S57_L001_R1_001   8.734123  74.514744     80  1.0

                                         25%       50%       75%
         sample
fraction MUZ120-31_S31_L001_R1_001  0.000237  0.000237  0.000237
         MUZ120-32_S32_L001_R1_001  0.000456  0.000456  0.000456
         MUZ120-33_S33_L001_R1_001  0.000461  0.000461  0.000461
         MUZ120-34_S34_L001_R1_001  0.000232  0.000232  0.000232
         MUZ120-35_S35_L001_R1_001  0.000209  0.000209  0.000209
         MUZ120-36_S36_L001_R1_001  0.000427  0.000427  0.000427
         MUZ120-37_S37_L001_R1_001  0.000198  0.000198  0.000396
         MUZ120-38_S38_L001_R1_001  0.000202  0.000202  0.000202
         MUZ120-39_S39_L001_R1_001  0.000219  0.000219  0.000219
         MUZ120-40_S40_L001_R1_001  0.000163  0.000163  0.000163
         MUZ120-41_S41_L001_R1_001  0.000175  0.000175  0.000351
         MUZ120-42_S42_L001_R1_001  0.000193  0.000193  0.000193
         MUZ120-43_S43_L001_R1_001  0.000456  0.000456  0.000456
         MUZ120-44_S44_L001_R1_001  0.000523  0.000523  0.000523
         MUZ120-45_S45_L001_R1_001  0.000759  0.000759  0.000759
         MUZ120-46_S46_L001_R1_001  0.000571  0.000571  0.000571
         MUZ120-47_S47_L001_R1_001  0.000646  0.000646  0.000646
         MUZ120-48_S48_L001_R1_001  0.000883  0.000883  0.000883
         MUZ120-49_S49_L001_R1_001  0.000247  0.000247  0.000247
         MUZ120-50_S50_L001_R1_001  0.000513  0.000513  0.000513
         MUZ120-51_S51_L001_R1_001  0.000414  0.000414  0.000414
         MUZ120-52_S52_L001_R1_001  0.000452  0.000452  0.000452
         MUZ120-53_S53_L001_R1_001  0.000492  0.000492  0.000492
         MUZ120-54_S54_L001_R1_001  0.000463  0.000463  0.000463
         MUZ120-55_S55_L001_R1_001  0.000169  0.000169  0.000169
         MUZ120-56_S56_L001_R1_001  0.000183  0.000183  0.000183
         MUZ120-57_S57_L001_R1_001  0.000188  0.000188  0.000188

In [44]:
describe(lc,cols=['count'],group='sample')

                                      mean  median       variance     std_dev  \
      sample
count MUZ120-31_S31_L001_R1_001  54.714286     1.0  110055.390977  331.745974
      MUZ120-32_S32_L001_R1_001  47.630435     1.0   99071.571498  314.756368
      MUZ120-33_S33_L001_R1_001  50.441860     1.0   63632.062016  252.253963
      MUZ120-34_S34_L001_R1_001  66.353846     1.0  162104.294712  402.621776
      MUZ120-35_S35_L001_R1_001  55.709302     1.0  252564.585089  502.558042
      MUZ120-36_S36_L001_R1_001  66.942857     1.0  151382.820168  389.079452
      MUZ120-37_S37_L001_R1_001  67.306667     1.0  298704.512793  546.538665
      MUZ120-38_S38_L001_R1_001  58.329412     1.0  138891.985434  372.682151
      MUZ120-39_S39_L001_R1_001  56.271605     1.0  213374.425309  461.924697
      MUZ120-40_S40_L001_R1_001  60.594059     1.0  171245.303564  413.817959
      MUZ120-41_S41_L001_R1_001  79.194444     1.0  433757.848983  658.602952
      MUZ120-42_S42_L001_R1_001  60.313953     1.0  151507.488509  389.239629
      MUZ120-43_S43_L001_R1_001  48.711111     1.0   61116.346465  247.217205
      MUZ120-44_S44_L001_R1_001  53.111111     1.0   95844.444444  309.587539
      MUZ120-45_S45_L001_R1_001  52.720000     1.0   66766.293333  258.391744
      MUZ120-46_S46_L001_R1_001  56.451613     1.0   89392.589247  298.985935
      MUZ120-47_S47_L001_R1_001  51.600000     1.0   40394.800000  200.984577
      MUZ120-48_S48_L001_R1_001  53.904762     1.0   49757.490476  223.063871
      MUZ120-49_S49_L001_R1_001  60.328358     1.0  127923.466305  357.663901
      MUZ120-50_S50_L001_R1_001  57.352941     1.0  107161.144385  327.354768
      MUZ120-51_S51_L001_R1_001  53.733333     1.0   69320.563636  263.287986
      MUZ120-52_S52_L001_R1_001  55.350000     1.0   65587.207692  256.099995
      MUZ120-53_S53_L001_R1_001  50.800000     1.0   97576.471795  312.372329
      MUZ120-54_S54_L001_R1_001  47.955556     1.0   98354.907071  313.615859
      MUZ120-55_S55_L001_R1_001  56.923077     1.0  289966.440627  538.485321
      MUZ120-56_S56_L001_R1_001  74.835616     1.0  213428.278158  461.982985
      MUZ120-57_S57_L001_R1_001  66.425000     1.0  303685.234810  551.076433

                                 mad  min     max   range   skewness  \
      sample
count MUZ120-31_S31_L001_R1_001  NaN  1.0  2451.0  2450.0   6.344116
      MUZ120-32_S32_L001_R1_001  NaN  1.0  2136.0  2135.0   6.559096
      MUZ120-33_S33_L001_R1_001  NaN  1.0  1576.0  1575.0   5.504120
      MUZ120-34_S34_L001_R1_001  NaN  1.0  3033.0  3032.0   6.655020
      MUZ120-35_S35_L001_R1_001  NaN  1.0  4662.0  4661.0   9.110785
      MUZ120-36_S36_L001_R1_001  NaN  1.0  2303.0  2302.0   5.659441
      MUZ120-37_S37_L001_R1_001  NaN  1.0  4734.0  4733.0   8.467692
      MUZ120-38_S38_L001_R1_001  NaN  1.0  2712.0  2711.0   6.421744
      MUZ120-39_S39_L001_R1_001  NaN  1.0  4151.0  4150.0   8.761694
      MUZ120-40_S40_L001_R1_001  NaN  1.0  3086.0  3085.0   6.910534
      MUZ120-41_S41_L001_R1_001  NaN  1.0  5590.0  5589.0   8.307431
      MUZ120-42_S42_L001_R1_001  NaN  1.0  2941.0  2940.0   6.575016
      MUZ120-43_S43_L001_R1_001  NaN  1.0  1573.0  1572.0   5.592348
      MUZ120-44_S44_L001_R1_001  NaN  1.0  1859.0  1858.0   5.746662
      MUZ120-45_S45_L001_R1_001  NaN  1.0  1293.0  1292.0   4.694851
      MUZ120-46_S46_L001_R1_001  NaN  1.0  1667.0  1666.0   5.290121
      MUZ120-47_S47_L001_R1_001  NaN  1.0   984.0   983.0   3.965126
      MUZ120-48_S48_L001_R1_001  NaN  1.0  1024.0  1023.0   4.201504
      MUZ120-49_S49_L001_R1_001  NaN  1.0  2672.0  2671.0   6.491168
      MUZ120-50_S50_L001_R1_001  NaN  1.0  1910.0  1909.0   5.570466
      MUZ120-51_S51_L001_R1_001  NaN  1.0  1616.0  1615.0   5.226300
      MUZ120-52_S52_L001_R1_001  NaN  1.0  1487.0  1486.0   4.912984
      MUZ120-53_S53_L001_R1_001  NaN  1.0  1977.0  1976.0   6.084615
      MUZ120-54_S54_L001_R1_001  NaN  1.0  2105.0  2104.0   6.482458
      MUZ120-55_S55_L001_R1_001  NaN  1.0  5491.0  5490.0  10.024901
      MUZ120-56_S56_L001_R1_001  NaN  1.0  3522.0  3521.0   6.580739
      MUZ120-57_S57_L001_R1_001  NaN  1.0  4926.0  4925.0   8.734123

                                  kurtosis  count     sum  25%  50%  75%
      sample
count MUZ120-31_S31_L001_R1_001  39.681758     77  4213.0  1.0  1.0  1.0
      MUZ120-32_S32_L001_R1_001  41.021911     46  2191.0  1.0  1.0  1.0
      MUZ120-33_S33_L001_R1_001  29.973192     43  2169.0  1.0  1.0  1.0
      MUZ120-34_S34_L001_R1_001  44.806615     65  4313.0  1.0  1.0  1.0
      MUZ120-35_S35_L001_R1_001  81.008219     86  4791.0  1.0  1.0  1.0
      MUZ120-36_S36_L001_R1_001  30.029323     35  2343.0  1.0  1.0  1.0
      MUZ120-37_S37_L001_R1_001  69.803572     75  5048.0  1.0  1.0  2.0
      MUZ120-38_S38_L001_R1_001  39.806366     85  4958.0  1.0  1.0  1.0
      MUZ120-39_S39_L001_R1_001  75.149848     81  4558.0  1.0  1.0  1.0
      MUZ120-40_S40_L001_R1_001  45.881758    101  6120.0  1.0  1.0  1.0
      MUZ120-41_S41_L001_R1_001  67.013642     72  5702.0  1.0  1.0  2.0
      MUZ120-42_S42_L001_R1_001  42.242834     86  5187.0  1.0  1.0  1.0
      MUZ120-43_S43_L001_R1_001  31.044384     45  2192.0  1.0  1.0  1.0
      MUZ120-44_S44_L001_R1_001  31.025682     36  1912.0  1.0  1.0  1.0
      MUZ120-45_S45_L001_R1_001  20.041639     25  1318.0  1.0  1.0  1.0
      MUZ120-46_S46_L001_R1_001  26.002033     31  1750.0  1.0  1.0  1.0
      MUZ120-47_S47_L001_R1_001  14.691118     30  1548.0  1.0  1.0  1.0
      MUZ120-48_S48_L001_R1_001  15.783342     21  1132.0  1.0  1.0  1.0
      MUZ120-49_S49_L001_R1_001  42.567687     67  4042.0  1.0  1.0  1.0
      MUZ120-50_S50_L001_R1_001  29.030167     34  1950.0  1.0  1.0  1.0
      MUZ120-51_S51_L001_R1_001  26.978755     45  2418.0  1.0  1.0  1.0
      MUZ120-52_S52_L001_R1_001  23.645592     40  2214.0  1.0  1.0  1.0
      MUZ120-53_S53_L001_R1_001  35.023618     40  2032.0  1.0  1.0  1.0
      MUZ120-54_S54_L001_R1_001  40.022426     45  2158.0  1.0  1.0  1.0
      MUZ120-55_S55_L001_R1_001  98.664031    104  5920.0  1.0  1.0  1.0
      MUZ120-56_S56_L001_R1_001  43.626499     73  5463.0  1.0  1.0  1.0
      MUZ120-57_S57_L001_R1_001  74.514744     80  5314.0  1.0  1.0  1.0

In [32]:
data[['Var1','Var2','Var3','Var4','Var5']].mean()

Var1    0.520137
Var2    0.395268
Var3    0.400387
Var4    0.509271
Var5    0.404557
dtype: float64

In [35]:
data[['Var1','Var2','Var3','Var4','Var5']].mode()

       Var1      Var2      Var3      Var4      Var5
0  0.058084  0.020584  0.046450  0.065052  0.034389
1  0.155995  0.181825  0.139494  0.097672  0.122038
2  0.156019  0.183405  0.199674  0.170524  0.184854
3  0.374540  0.212339  0.292145  0.304614  0.258780
4  0.598658  0.291229  0.366362  0.440152  0.311711
5  0.601115  0.304242  0.456070  0.607545  0.495177
6  0.708073  0.431945  0.514234  0.684233  0.520068
7  0.731994  0.524756  0.592415  0.808397  0.546710
8  0.866176  0.832443  0.611853  0.948886  0.662522
9  0.950714  0.969910  0.785176  0.965632  0.909320

In [39]:
describe(data,cols=['Var1','Var2','Var3','Var4','Var5'])

,mean,median,variance,std_dev,mad,min,max,range,skewness,kurtosis,count,sum,25%,50%,75%
Var1,0.520137,0.599887,0.099771,0.315866,0.245818,0.058084,0.950714,0.892631,-0.222491,-1.347470,10,5.201367,0.210649,0.599887,0.726014
Var2,0.395268,0.297736,0.091428,0.302371,0.125060,0.020584,0.969910,0.949325,0.829070,-0.475119,10,3.952678,0.190638,0.297736,0.501554
Var3,0.400387,0.411216,0.054690,0.233860,0.190918,0.046450,0.785176,0.738726,0.033596,-1.037475,10,4.003872,0.222791,0.411216,0.572870
Var4,0.509271,0.523849,0.117714,0.343095,0.318937,0.065052,0.965632,0.900580,0.022949,-1.464473,10,5.092707,0.204047,0.523849,0.777356
Var5,0.404557,0.403444,0.073120,0.270406,0.181627,0.034389,0.909320,0.874932,0.374111,-0.737048,10,4.045570,0.203336,0.403444,0.540050

In [22]:
data.pivot?

Signature:
data.pivot(
    *,
    columns,
    index=typing.Literal[<no_default>],
    values=typing.Literal[<no_default>],
) -> 'DataFrame'
Docstring:
Return reshaped DataFrame organized by given index / column values.

Reshape data (produce a "pivot" table) based on column values. Uses
unique values from specified `index` / `columns` to form axes of the
resulting DataFrame. This function does not support data
aggregation, multiple values will result in a MultiIndex in the
columns. See the :ref:`User Guide <reshaping>` for more on reshaping.

Parameters
----------
columns : str or object or a list of str
    Column to use to make new frame's columns.

    .. versionchanged:: 1.1.0
       Also accept list of columns names.

index : str or object or a list of str, optional
    Column to use to make new frame's index. If not given, uses existing index.

    .. versionchanged:: 1.1.0
       Also accept list of index names.

values : str, object or a list of the previous, optional
    Column(s) to use for populating new frame's values. If not
    specified, all remaining columns will be used and the result will
    have hierarchically indexed columns.

Returns
-------
DataFrame
    Returns reshaped DataFrame.

Raises
------
ValueError:
    When there are any `index`, `columns` combinations with multiple
    values. `DataFrame.pivot_table` when you need to aggregate.

See Also
--------
DataFrame.pivot_table : Generalization of pivot that can handle
    duplicate values for one index/column pair.
DataFrame.unstack : Pivot based on the index values instead of a
    column.
wide_to_long : Wide panel to long format. Less flexible but more
    user-friendly than melt.

Notes
-----
For finer-tuned control, see hierarchical indexing documentation along
with the related stack/unstack methods.

Reference :ref:`the user guide <reshaping.pivot>` for more examples.

Examples
--------
>>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
...                            'two'],
...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
...                    'baz': [1, 2, 3, 4, 5, 6],
...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
>>> df
    foo   bar  baz  zoo
0   one   A    1    x
1   one   B    2    y
2   one   C    3    z
3   two   A    4    q
4   two   B    5    w
5   two   C    6    t

>>> df.pivot(index='foo', columns='bar', values='baz')
bar  A   B   C
foo
one  1   2   3
two  4   5   6

>>> df.pivot(index='foo', columns='bar')['baz']
bar  A   B   C
foo
one  1   2   3
two  4   5   6

>>> df.pivot(index='foo', columns='bar', values=['baz', 'zoo'])
      baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t

You could also assign a list of column names or a list of index names.

>>> df = pd.DataFrame({
...        "lev1": [1, 1, 1, 2, 2, 2],
...        "lev2": [1, 1, 2, 1, 1, 2],
...        "lev3": [1, 2, 1, 2, 1, 2],
...        "lev4": [1, 2, 3, 4, 5, 6],
...        "values": [0, 1, 2, 3, 4, 5]})
>>> df
    lev1 lev2 lev3 lev4 values
0   1    1    1    1    0
1   1    1    2    2    1
2   1    2    1    3    2
3   2    1    2    4    3
4   2    1    1    5    4
5   2    2    2    6    5

>>> df.pivot(index="lev1", columns=["lev2", "lev3"], values="values")
lev2    1         2
lev3    1    2    1    2
lev1
1     0.0  1.0  2.0  NaN
2     4.0  3.0  NaN  5.0

>>> df.pivot(index=["lev1", "lev2"], columns=["lev3"], values="values")
      lev3    1    2
lev1  lev2
   1     1  0.0  1.0
         2  2.0  NaN
   2     1  4.0  3.0
         2  NaN  5.0

A ValueError is raised if there are any duplicates.

>>> df = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'],
...                    "bar": ['A', 'A', 'B', 'C'],
...                    "baz": [1, 2, 3, 4]})
>>> df
   foo bar  baz
0  one   A    1
1  one   A    2
2  two   B    3
3  two   C    4

Notice that the first two rows are the same for our `index`
and `columns` arguments.

>>> df.pivot(index='foo', columns='bar', values='baz')
Traceback (most recent call last):
   ...
ValueError: Index contains duplicate entries, cannot reshape
File:      ~/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py
Type:      method

In [6]:
data.groupby?

Signature:
data.groupby(
    by=None,
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    as_index: 'bool' = True,
    sort: 'bool' = True,
    group_keys: 'bool' = True,
    observed: 'bool' = False,
    dropna: 'bool' = True,
) -> 'DataFrameGroupBy'
Docstring:
Group DataFrame using a mapper or by a Series of columns.

A groupby operation involves some combination of splitting the
object, applying a function, and combining the results. This can be
used to group large amounts of data and compute operations on these
groups.

Parameters
----------
by : mapping, function, label, pd.Grouper or list of such
    Used to determine the groups for the groupby.
    If ``by`` is a function, it's called on each value of the object's
    index. If a dict or Series is passed, the Series or dict VALUES
    will be used to determine the groups (the Series' values are first
    aligned; see ``.align()`` method). If a list or ndarray of length
    equal to the selected axis is passed (see the `groupby user guide
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups>`_),
    the values are used as-is to determine the groups. A label or list
    of labels may be passed to group by the columns in ``self``.
    Notice that a tuple is interpreted as a (single) key.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Split along rows (0) or columns (1). For `Series` this parameter
    is unused and defaults to 0.
level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
    level or levels. Do not specify both ``by`` and ``level``.
as_index : bool, default True
    For aggregated output, return object with group labels as the
    index. Only relevant for DataFrame input. as_index=False is
    effectively "SQL-style" grouped output.
sort : bool, default True
    Sort group keys. Get better performance by turning this off.
    Note this does not influence the order of observations within each
    group. Groupby preserves the order of rows within each group.

    .. versionchanged:: 2.0.0

        Specifying ``sort=False`` with an ordered categorical grouper will no
        longer sort the values.

group_keys : bool, default True
    When calling apply and the ``by`` argument produces a like-indexed
    (i.e. :ref:`a transform <groupby.transform>`) result, add group keys to
    index to identify pieces. By default group keys are not included
    when the result's index (and column) labels match the inputs, and
    are included otherwise.

    .. versionchanged:: 1.5.0

       Warns that ``group_keys`` will no longer be ignored when the
       result from ``apply`` is a like-indexed Series or DataFrame.
       Specify ``group_keys`` explicitly to include the group keys or
       not.

    .. versionchanged:: 2.0.0

       ``group_keys`` now defaults to ``True``.

observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.
dropna : bool, default True
    If True, and if group keys contain NA values, NA values together
    with row/column will be dropped.
    If False, NA values will also be treated as the key in groups.

    .. versionadded:: 1.1.0

Returns
-------
DataFrameGroupBy
    Returns a groupby object that contains information about the groups.

See Also
--------
resample : Convenience method for frequency conversion and resampling
    of time series.

Notes
-----
See the `user guide
<https://pandas.pydata.org/pandas-docs/stable/groupby.html>`__ for more
detailed usage and examples, including splitting an object into groups,
iterating through groups, selecting a group, aggregation, and more.

Examples
--------
>>> df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
...                               'Parrot', 'Parrot'],
...                    'Max Speed': [380., 370., 24., 26.]})
>>> df
   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0
>>> df.groupby(['Animal']).mean()
        Max Speed
Animal
Falcon      375.0
Parrot       25.0

**Hierarchical Indexes**

We can groupby different levels of a hierarchical index
using the `level` parameter:

>>> arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
...           ['Captive', 'Wild', 'Captive', 'Wild']]
>>> index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
>>> df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
...                   index=index)
>>> df
                Max Speed
Animal Type
Falcon Captive      390.0
       Wild         350.0
Parrot Captive       30.0
       Wild          20.0
>>> df.groupby(level=0).mean()
        Max Speed
Animal
Falcon      370.0
Parrot       25.0
>>> df.groupby(level="Type").mean()
         Max Speed
Type
Captive      210.0
Wild         185.0

We can also choose to include NA in group keys or not by setting
`dropna` parameter, the default setting is `True`.

>>> l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
>>> df = pd.DataFrame(l, columns=["a", "b", "c"])

>>> df.groupby(by=["b"]).sum()
    a   c
b
1.0 2   3
2.0 2   5

>>> df.groupby(by=["b"], dropna=False).sum()
    a   c
b
1.0 2   3
2.0 2   5
NaN 1   4

>>> l = [["a", 12, 12], [None, 12.3, 33.], ["b", 12.3, 123], ["a", 1, 1]]
>>> df = pd.DataFrame(l, columns=["a", "b", "c"])

>>> df.groupby(by="a").sum()
    b     c
a
a   13.0   13.0
b   12.3  123.0

>>> df.groupby(by="a", dropna=False).sum()
    b     c
a
a   13.0   13.0
b   12.3  123.0
NaN 12.3   33.0

When using ``.apply()``, use ``group_keys`` to include or exclude the group keys.
The ``group_keys`` argument defaults to ``True`` (include).

>>> df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
...                               'Parrot', 'Parrot'],
...                    'Max Speed': [380., 370., 24., 26.]})
>>> df.groupby("Animal", group_keys=True).apply(lambda x: x)
          Animal  Max Speed
Animal
Falcon 0  Falcon      380.0
       1  Falcon      370.0
Parrot 2  Parrot       24.0
       3  Parrot       26.0

>>> df.groupby("Animal", group_keys=False).apply(lambda x: x)
   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0
File:      ~/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py
Type:      method

# Statistical Test Flow Chart: test()

In [ ]:
''' test: Statistical test flow chart
        question: difference, correlation, categories
        factors: # of factors
        same: same (True) or different (False) subjects
        compare: list of comparisons
        para: parameteric (True) or nonparametric (False)
    Dependencies:
'''
def test(df: pd.DataFrame(), compare: list(), question: str(), factors=1, same=False, para=True):

    if question=='difference':
        if factors==1:
            if not same:
                if para==True:
                    if len(compare)==2:
                        print('Statistical Test: T-test \nAdvice: Only use if you have two groups or if you are comparing just two of the n groups and are not concerned about inflating the Type I error rate (e.g., False Positives).')
                        t_stat, p_value = stats.ttest_ind(df[compare[0]],df[compare[1]])
                        return pd.DataFrame({'t_stat': t_stat, 'p_value': p_value},index=pd.Index([','.join(compare)],name='compare')).reset_index()
                    elif len(compare)>2:
                        print('Statistical Test: 1-way Anova\nAdvice: If you want to compare all three groups simultaneously to determine if there is a significant difference in their means.')
                        print('Follow up with Tukey\'s Honestly Significant Difference (HSD) Test,Bonferroni Correction for t-test, Holm’s Sequential Bonferroni Procedure')
                        f_stat, p_value = stats.f_oneway(*(df[col] for col in compare))
                        return pd.DataFrame({'f_stat': f_stat, 'p_value': p_value},index=pd.Index([','.join(compare)],name='compare')).reset_index()
                    else: print('Error: Invalid compare. List needs to contain 2 or more stings')
                else:
                    print('Statistical Test: Mann Whitney U Test\nWIP...')
                    f_stat, p_value = stats.f_oneway(df[compare])
            
            else:
                if para==True:
                    if len(compare)==2:
                        print('Statistical Test: Paired T-test \nWIP...')
                        t_stat, p_value, dof = stats.ttest_ind(df[compare])
                        return pd.DataFrame({'t_stat': t_stat, 'p_value': p_value, 'dof':dof})
                    elif len(compare)>2:
                        print('Statistical Test: Repeated 1-way Anova\nWIP...')
                        f_stat, p_value = stats.f_oneway(df[compare])
                    else: print('Error: Invalid compare. List needs to contain 2 or more stings')
                else: return ''
        elif factors>1: print('Statistical Test: 2 way anova, General Linear (Mixed) Model, etc.\nNot Included...')
        else: print('Error: Invalid factors. Number needs to be greater or equal to 1.')
    
    elif question=='correlation':
        return ''
    
    elif question=='category':
        return ''
    
    else:
        print('Error: Invalid question. Needs to be difference, correlation, or category.')

need to reformat to tidy data and then it will be good for pairwise turkey_hsd

In [65]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
pairwise_tukeyhsd?

Signature: pairwise_tukeyhsd(endog, groups, alpha=0.05)
Docstring:
Calculate all pairwise comparisons with TukeyHSD confidence intervals

Parameters
----------
endog : ndarray, float, 1d
    response variable
groups : ndarray, 1d
    array with groups, can be string or integers
alpha : float
    significance level for the test

Returns
-------
results : TukeyHSDResults instance
    A results class containing relevant data and some post-hoc
    calculations, including adjusted p-value

Notes
-----
This is just a wrapper around tukeyhsd method of MultiComparison

See Also
--------
MultiComparison
tukeyhsd
statsmodels.sandbox.stats.multicomp.TukeyHSDResults
File:      ~/anaconda3/lib/python3.11/site-packages/statsmodels/stats/multicomp.py
Type:      function

In [67]:
pairwise_tukeyhsd(endog=data[['Var1','Var2','Var3','Var4','Var5']],groups=['Var1','Var2','Var3','Var4','Var5'])

ValueError: data has 10 elements and groups has 5

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Assuming you have a DataFrame df with a column 'values' and a column 'group'
tukey_result = pairwise_tukeyhsd(data['values'], data['group'], alpha=0.05)
print(tukey_result)

Post-hoc tests are used after a one-way ANOVA when you find a statistically significant difference between the group means. These tests help you determine which specific groups differ from each other. Here are some common post-hoc tests used after a one-way ANOVA:

1. Tukey's Honestly Significant Difference (HSD) Test
Purpose: The most commonly used post-hoc test, Tukey's HSD, compares all possible pairs of group means to identify which ones differ significantly.
Usage: It's suitable when you have equal or unequal group sizes.
Implementation:
In Python, you can use pairwise_tukeyhsd from statsmodels.stats.multicomp.
python
Copy code
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Assuming you have a DataFrame df with a column 'values' and a column 'group'
tukey_result = pairwise_tukeyhsd(df['values'], df['group'], alpha=0.05)
print(tukey_result)
2. Bonferroni Correction
Purpose: Adjusts the significance level to account for the number of comparisons being made, reducing the risk of Type I errors.
Usage: You apply it when performing multiple pairwise t-tests. It's a more conservative approach.
Implementation:
You would manually adjust the p-value threshold by dividing the original alpha level by the number of comparisons.
3. Scheffé's Test
Purpose: A very conservative test, Scheffé's test can be used when comparing complex comparisons (not just pairwise). It's suitable when you suspect non-pairwise differences.
Usage: It's less commonly used due to its conservative nature.
Implementation: It's available in some statistical software, but not directly implemented in popular Python libraries.
4. Dunnett's Test
Purpose: Compares multiple treatment groups against a single control group.
Usage: Ideal when you have one control group and want to compare it against several other groups.
Implementation: Specialized packages or functions may be required for this in Python.
5. Holm’s Sequential Bonferroni Procedure
Purpose: A step-down procedure that adjusts p-values to control the family-wise error rate. It's less conservative than the Bonferroni correction.
Usage: Useful when dealing with multiple comparisons.
Implementation: You can use multipletests from statsmodels.
python
Copy code
from statsmodels.stats.multitest import multipletests

# Assuming pvals is a list or array of p-values from multiple tests
pvals_corrected = multipletests(pvals, method='holm')
print(pvals_corrected)
6. Dunn’s Test
Purpose: A non-parametric test used when the ANOVA assumptions are violated. It is used after a Kruskal-Wallis test (non-parametric alternative to ANOVA).
Usage: Suitable when you have non-normally distributed data.
Implementation: The scikit-posthocs package can be used for Dunn's test in Python.

In [57]:
stats.f_oneway(data[['Var1','Var2','Var3','Var4','Var5']])

TypeError: at least two inputs are required; got 1.

In [59]:
data

       Var1      Var2      Var3      Var4      Var5  c
0  0.374540  0.020584  0.611853  0.607545  0.122038  X
1  0.950714  0.969910  0.139494  0.170524  0.495177  X
2  0.731994  0.832443  0.292145  0.065052  0.034389  Y
3  0.598658  0.212339  0.366362  0.948886  0.909320  Y
4  0.156019  0.181825  0.456070  0.965632  0.258780  Y
5  0.155995  0.183405  0.785176  0.808397  0.662522  X
6  0.058084  0.304242  0.199674  0.304614  0.311711  X
7  0.866176  0.524756  0.514234  0.097672  0.520068  Y
8  0.601115  0.431945  0.592415  0.684233  0.546710  Y
9  0.708073  0.291229  0.046450  0.440152  0.184854  Y

In [62]:
compare = ['Var1','Var2']
t_stat, p_value = stats.ttest_ind(data[compare[0]],data[compare[1]])
pd.DataFrame({'t_stat': t_stat, 'p_value': p_value},index=pd.Index([','.join(compare)],name='compare')).reset_index()

     compare    t_stat   p_value
0  Var1,Var2  0.903049  0.378427

In [64]:
compare = ['Var1','Var2','Var3']
f_stat, p_value = stats.f_oneway(*(data[col] for col in compare))
pd.DataFrame({'f_stat': f_stat, 'p_value': p_value},index=pd.Index([','.join(compare)],name='compare')).reset_index()

          compare    f_stat  p_value
0  Var1,Var2,Var3  0.609184   0.5511

In [54]:
stats.f_oneway?

Signature: stats.f_oneway(*samples, axis=0)
Docstring:
Perform one-way ANOVA.

The one-way ANOVA tests the null hypothesis that two or more groups have
the same population mean.  The test is applied to samples from two or
more groups, possibly with differing sizes.

Parameters
----------
sample1, sample2, ... : array_like
    The sample measurements for each group.  There must be at least
    two arguments.  If the arrays are multidimensional, then all the
    dimensions of the array must be the same except for `axis`.
axis : int, optional
    Axis of the input arrays along which the test is applied.
    Default is 0.

Returns
-------
statistic : float
    The computed F statistic of the test.
pvalue : float
    The associated p-value from the F distribution.

Warns
-----
`~scipy.stats.ConstantInputWarning`
    Raised if all values within each of the input arrays are identical.
    In this case the F statistic is either infinite or isn't defined,
    so ``np.inf`` or ``np.nan`` is returned.

`~scipy.stats.DegenerateDataWarning`
    Raised if the length of any input array is 0, or if all the input
    arrays have length 1.  ``np.nan`` is returned for the F statistic
    and the p-value in these cases.

Notes
-----
The ANOVA test has important assumptions that must be satisfied in order
for the associated p-value to be valid.

1. The samples are independent.
2. Each sample is from a normally distributed population.
3. The population standard deviations of the groups are all equal.  This
   property is known as homoscedasticity.

If these assumptions are not true for a given set of data, it may still
be possible to use the Kruskal-Wallis H-test (`scipy.stats.kruskal`) or
the Alexander-Govern test (`scipy.stats.alexandergovern`) although with
some loss of power.

The length of each group must be at least one, and there must be at
least one group with length greater than one.  If these conditions
are not satisfied, a warning is generated and (``np.nan``, ``np.nan``)
is returned.

If all values in each group are identical, and there exist at least two
groups with different values, the function generates a warning and
returns (``np.inf``, 0).

If all values in all groups are the same, function generates a warning
and returns (``np.nan``, ``np.nan``).

The algorithm is from Heiman [2]_, pp.394-7.

References
----------
.. [1] R. Lowry, "Concepts and Applications of Inferential Statistics",
       Chapter 14, 2014, http://vassarstats.net/textbook/

.. [2] G.W. Heiman, "Understanding research methods and statistics: An
       integrated introduction for psychology", Houghton, Mifflin and
       Company, 2001.

.. [3] G.H. McDonald, "Handbook of Biological Statistics", One-way ANOVA.
       http://www.biostathandbook.com/onewayanova.html

Examples
--------
>>> import numpy as np
>>> from scipy.stats import f_oneway

Here are some data [3]_ on a shell measurement (the length of the anterior
adductor muscle scar, standardized by dividing by length) in the mussel
Mytilus trossulus from five locations: Tillamook, Oregon; Newport, Oregon;
Petersburg, Alaska; Magadan, Russia; and Tvarminne, Finland, taken from a
much larger data set used in McDonald et al. (1991).

>>> tillamook = [0.0571, 0.0813, 0.0831, 0.0976, 0.0817, 0.0859, 0.0735,
...              0.0659, 0.0923, 0.0836]
>>> newport = [0.0873, 0.0662, 0.0672, 0.0819, 0.0749, 0.0649, 0.0835,
...            0.0725]
>>> petersburg = [0.0974, 0.1352, 0.0817, 0.1016, 0.0968, 0.1064, 0.105]
>>> magadan = [0.1033, 0.0915, 0.0781, 0.0685, 0.0677, 0.0697, 0.0764,
...            0.0689]
>>> tvarminne = [0.0703, 0.1026, 0.0956, 0.0973, 0.1039, 0.1045]
>>> f_oneway(tillamook, newport, petersburg, magadan, tvarminne)
F_onewayResult(statistic=7.121019471642447, pvalue=0.0002812242314534544)

`f_oneway` accepts multidimensional input arrays.  When the inputs
are multidimensional and `axis` is not given, the test is performed
along the first axis of the input arrays.  For the following data, the
test is performed three times, once for each column.

>>> a = np.array([[9.87, 9.03, 6.81],
...               [7.18, 8.35, 7.00],
...               [8.39, 7.58, 7.68],
...               [7.45, 6.33, 9.35],
...               [6.41, 7.10, 9.33],
...               [8.00, 8.24, 8.44]])
>>> b = np.array([[6.35, 7.30, 7.16],
...               [6.65, 6.68, 7.63],
...               [5.72, 7.73, 6.72],
...               [7.01, 9.19, 7.41],
...               [7.75, 7.87, 8.30],
...               [6.90, 7.97, 6.97]])
>>> c = np.array([[3.31, 8.77, 1.01],
...               [8.25, 3.24, 3.62],
...               [6.32, 8.81, 5.19],
...               [7.48, 8.83, 8.91],
...               [8.59, 6.01, 6.07],
...               [3.07, 9.72, 7.48]])
>>> F, p = f_oneway(a, b, c)
>>> F
array([1.75676344, 0.03701228, 3.76439349])
>>> p
array([0.20630784, 0.96375203, 0.04733157])
File:      ~/anaconda3/lib/python3.11/site-packages/scipy/stats/_stats_py.py
Type:      function

In [53]:
stats.ttest_ind?

Signature:
stats.ttest_ind(
    a,
    b,
    axis=0,
    equal_var=True,
    nan_policy='propagate',
    permutations=None,
    random_state=None,
    alternative='two-sided',
    trim=0,
    *,
    keepdims=False,
)
Docstring:
Calculate the T-test for the means of *two independent* samples of scores.

This is a test for the null hypothesis that 2 independent samples
have identical average (expected) values. This test assumes that the
populations have identical variances by default.

Parameters
----------
a, b : array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int or None, default: 0
    If an int, the axis of the input along which to compute the statistic.
    The statistic of each axis-slice (e.g. row) of the input will appear in a
    corresponding element of the output.
    If ``None``, the input will be raveled before computing the statistic.
equal_var : bool, optional
    If True (default), perform a standard independent 2 sample test
    that assumes equal population variances [1]_.
    If False, perform Welch's t-test, which does not assume equal
    population variance [2]_.

    .. versionadded:: 0.11.0
nan_policy : {'propagate', 'omit', 'raise'}
    Defines how to handle input NaNs.

    - ``propagate``: if a NaN is present in the axis slice (e.g. row) along
      which the  statistic is computed, the corresponding entry of the output
      will be NaN.
    - ``omit``: NaNs will be omitted when performing the calculation.
      If insufficient data remains in the axis slice along which the
      statistic is computed, the corresponding entry of the output will be
      NaN.
    - ``raise``: if a NaN is present, a ``ValueError`` will be raised.
permutations : non-negative int, np.inf, or None (default), optional
    If 0 or None (default), use the t-distribution to calculate p-values.
    Otherwise, `permutations` is  the number of random permutations that
    will be used to estimate p-values using a permutation test. If
    `permutations` equals or exceeds the number of distinct partitions of
    the pooled data, an exact test is performed instead (i.e. each
    distinct partition is used exactly once). See Notes for details.

    .. versionadded:: 1.7.0
random_state : {None, int, `numpy.random.Generator`,
        `numpy.random.RandomState`}, optional

    If `seed` is None (or `np.random`), the `numpy.random.RandomState`
    singleton is used.
    If `seed` is an int, a new ``RandomState`` instance is used,
    seeded with `seed`.
    If `seed` is already a ``Generator`` or ``RandomState`` instance then
    that instance is used.

    Pseudorandom number generator state used to generate permutations
    (used only when `permutations` is not None).

    .. versionadded:: 1.7.0
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis.
    The following options are available (default is 'two-sided'):

    * 'two-sided': the means of the distributions underlying the samples
      are unequal.
    * 'less': the mean of the distribution underlying the first sample
      is less than the mean of the distribution underlying the second
      sample.
    * 'greater': the mean of the distribution underlying the first
      sample is greater than the mean of the distribution underlying
      the second sample.

    .. versionadded:: 1.6.0
trim : float, optional
    If nonzero, performs a trimmed (Yuen's) t-test.
    Defines the fraction of elements to be trimmed from each end of the
    input samples. If 0 (default), no elements will be trimmed from either
    side. The number of trimmed elements from each tail is the floor of the
    trim times the number of elements. Valid range is [0, .5).

    .. versionadded:: 1.7
keepdims : bool, default: False
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

Returns
-------
result : `~scipy.stats._result_classes.TtestResult`
    An object with the following attributes:

    statistic : float or ndarray
        The t-statistic.
    pvalue : float or ndarray
        The p-value associated with the given alternative.
    df : float or ndarray
        The number of degrees of freedom used in calculation of the
        t-statistic. This is always NaN for a permutation t-test.

        .. versionadded:: 1.11.0

    The object also has the following method:

    confidence_interval(confidence_level=0.95)
        Computes a confidence interval around the difference in
        population means for the given confidence level.
        The confidence interval is returned in a ``namedtuple`` with
        fields ``low`` and ``high``.
        When a permutation t-test is performed, the confidence interval
        is not computed, and fields ``low`` and ``high`` contain NaN.

        .. versionadded:: 1.11.0

Notes
-----
Suppose we observe two independent samples, e.g. flower petal lengths, and
we are considering whether the two samples were drawn from the same
population (e.g. the same species of flower or two species with similar
petal characteristics) or two different populations.

The t-test quantifies the difference between the arithmetic means
of the two samples. The p-value quantifies the probability of observing
as or more extreme values assuming the null hypothesis, that the
samples are drawn from populations with the same population means, is true.
A p-value larger than a chosen threshold (e.g. 5% or 1%) indicates that
our observation is not so unlikely to have occurred by chance. Therefore,
we do not reject the null hypothesis of equal population means.
If the p-value is smaller than our threshold, then we have evidence
against the null hypothesis of equal population means.

By default, the p-value is determined by comparing the t-statistic of the
observed data against a theoretical t-distribution.
When ``1 < permutations < binom(n, k)``, where

* ``k`` is the number of observations in `a`,
* ``n`` is the total number of observations in `a` and `b`, and
* ``binom(n, k)`` is the binomial coefficient (``n`` choose ``k``),

the data are pooled (concatenated), randomly assigned to either group `a`
or `b`, and the t-statistic is calculated. This process is performed
repeatedly (`permutation` times), generating a distribution of the
t-statistic under the null hypothesis, and the t-statistic of the observed
data is compared to this distribution to determine the p-value.
Specifically, the p-value reported is the "achieved significance level"
(ASL) as defined in 4.4 of [3]_. Note that there are other ways of
estimating p-values using randomized permutation tests; for other
options, see the more general `permutation_test`.

When ``permutations >= binom(n, k)``, an exact test is performed: the data
are partitioned between the groups in each distinct way exactly once.

The permutation test can be computationally expensive and not necessarily
more accurate than the analytical test, but it does not make strong
assumptions about the shape of the underlying distribution.

Use of trimming is commonly referred to as the trimmed t-test. At times
called Yuen's t-test, this is an extension of Welch's t-test, with the
difference being the use of winsorized means in calculation of the variance
and the trimmed sample size in calculation of the statistic. Trimming is
recommended if the underlying distribution is long-tailed or contaminated
with outliers [4]_.

The statistic is calculated as ``(np.mean(a) - np.mean(b))/se``, where
``se`` is the standard error. Therefore, the statistic will be positive
when the sample mean of `a` is greater than the sample mean of `b` and
negative when the sample mean of `a` is less than the sample mean of
`b`.

Beginning in SciPy 1.9, ``np.matrix`` inputs (not recommended for new
code) are converted to ``np.ndarray`` before the calculation is performed. In
this case, the output will be a scalar or ``np.ndarray`` of appropriate shape
rather than a 2D ``np.matrix``. Similarly, while masked elements of masked
arrays are ignored, the output will be a scalar or ``np.ndarray`` rather than a
masked array with ``mask=False``.

References
----------
.. [1] https://en.wikipedia.org/wiki/T-test#Independent_two-sample_t-test

.. [2] https://en.wikipedia.org/wiki/Welch%27s_t-test

.. [3] B. Efron and T. Hastie. Computer Age Statistical Inference. (2016).

.. [4] Yuen, Karen K. "The Two-Sample Trimmed t for Unequal Population
       Variances." Biometrika, vol. 61, no. 1, 1974, pp. 165-170. JSTOR,
       www.jstor.org/stable/2334299. Accessed 30 Mar. 2021.

.. [5] Yuen, Karen K., and W. J. Dixon. "The Approximate Behaviour and
       Performance of the Two-Sample Trimmed t." Biometrika, vol. 60,
       no. 2, 1973, pp. 369-374. JSTOR, www.jstor.org/stable/2334550.
       Accessed 30 Mar. 2021.

Examples
--------
>>> import numpy as np
>>> from scipy import stats
>>> rng = np.random.default_rng()

Test with sample with identical means:

>>> rvs1 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
>>> rvs2 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
>>> stats.ttest_ind(rvs1, rvs2)
Ttest_indResult(statistic=-0.4390847099199348, pvalue=0.6606952038870015)
>>> stats.ttest_ind(rvs1, rvs2, equal_var=False)
Ttest_indResult(statistic=-0.4390847099199348, pvalue=0.6606952553131064)

`ttest_ind` underestimates p for unequal variances:

>>> rvs3 = stats.norm.rvs(loc=5, scale=20, size=500, random_state=rng)
>>> stats.ttest_ind(rvs1, rvs3)
Ttest_indResult(statistic=-1.6370984482905417, pvalue=0.1019251574705033)
>>> stats.ttest_ind(rvs1, rvs3, equal_var=False)
Ttest_indResult(statistic=-1.637098448290542, pvalue=0.10202110497954867)

When ``n1 != n2``, the equal variance t-statistic is no longer equal to the
unequal variance t-statistic:

>>> rvs4 = stats.norm.rvs(loc=5, scale=20, size=100, random_state=rng)
>>> stats.ttest_ind(rvs1, rvs4)
Ttest_indResult(statistic=-1.9481646859513422, pvalue=0.05186270935842703)
>>> stats.ttest_ind(rvs1, rvs4, equal_var=False)
Ttest_indResult(statistic=-1.3146566100751664, pvalue=0.1913495266513811)

T-test with different means, variance, and n:

>>> rvs5 = stats.norm.rvs(loc=8, scale=20, size=100, random_state=rng)
>>> stats.ttest_ind(rvs1, rvs5)
Ttest_indResult(statistic=-2.8415950600298774, pvalue=0.0046418707568707885)
>>> stats.ttest_ind(rvs1, rvs5, equal_var=False)
Ttest_indResult(statistic=-1.8686598649188084, pvalue=0.06434714193919686)

When performing a permutation test, more permutations typically yields
more accurate results. Use a ``np.random.Generator`` to ensure
reproducibility:

>>> stats.ttest_ind(rvs1, rvs5, permutations=10000,
...                 random_state=rng)
Ttest_indResult(statistic=-2.8415950600298774, pvalue=0.0052994700529947)

Take these two samples, one of which has an extreme tail.

>>> a = (56, 128.6, 12, 123.8, 64.34, 78, 763.3)
>>> b = (1.1, 2.9, 4.2)

Use the `trim` keyword to perform a trimmed (Yuen) t-test. For example,
using 20% trimming, ``trim=.2``, the test will reduce the impact of one
(``np.floor(trim*len(a))``) element from each tail of sample `a`. It will
have no effect on sample `b` because ``np.floor(trim*len(b))`` is 0.

>>> stats.ttest_ind(a, b, trim=.2)
Ttest_indResult(statistic=3.4463884028073513,
                pvalue=0.01369338726499547)
File:      ~/anaconda3/lib/python3.11/site-packages/scipy/stats/_stats_py.py
Type:      function